version: '3'
services:
  todoapp:
    image: node:16.13-alpine
    working_dir: /app
    tty: true
    ports:
      - '13001:13001'
    volumes:
      - '.:/app'
    command: sh -c "npm install && npm run dev"
