version: "3"
services:
  todoapp:
    image: node:16.13-alpine
    working_dir: /app
    tty: true
    ports:
      - "3001:3001"
    volumes:
      - ".:/app"
    command: sh -c "npm install && npm run dev"
